import requests
import os
from dotenv import load_dotenv

load_dotenv()
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO", "achux11/-ticket-agent")

def create_github_issue(title, body, severity):
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    }

    label_map = {
        "Critical": "critical",
        "High": "high priority",
        "Medium": "medium priority",
        "Low": "low priority"
    }

    data = {
        "title": "[BUG] " + title,
        "body": body,
        "labels": [label_map.get(severity, "bug"), "bug"]
    }

    try:
        response = requests.post(url, headers=headers, json=data, timeout=30)

        if response.status_code == 422:
            data.pop("labels")
            response = requests.post(url, headers=headers, json=data, timeout=30)

        response.raise_for_status()
        result = response.json()

        return {
            "success": True,
            "issue_number": result["number"],
            "issue_url": result["html_url"],
            "title": result["title"]
        }

    except requests.exceptions.HTTPError as e:
        return {
            "success": False,
            "error": "GitHub API error: " + str(e.response.status_code)
        }
    except Exception as e:
        return {
            "success": False,
            "error": "Error: " + str(e)
        }


def format_issue_body(bug, code):
    lines = [
        "## Bug Report",
        "",
        "**Severity:** " + bug["severity"],
        "**Category:** " + bug["category"],
        "",
        "## Description",
        bug["description"],
        "",
        "## Problematic Code",
        bug.get("code_snippet", "See full code below"),
        "",
        "## Suggested Fix",
        bug["suggested_fix"],
        "",
        "## Full Code Submitted",
        code[:2000],
        "",
        "---",
        "This ticket was automatically generated by the Bug Ticket Agent"
    ]
    return "\n".join(lines)


def get_all_issues():
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }

    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        return []